### ISSUE TITLE
JavaScript-Start-Profiling header on individual <script/> HTTP responses

### ISSUE THREAD

**Issue by vdjeric** [vdjeric/js-self-profiling#2]
Question asked by msoInit on the [WICG discourse thread](https://discourse.wicg.io/t/proposal-an-api-to-allow-webpage-javascript-to-profile-its-own-performance/2818/3?u=vdjeric):

> Should the JavaScript-Start-Profiling header be on individual <script/> HTTP responses instead of at the page level?

**Comment by vdjeric** [comment]
I was thinking it should be at the document level (page or iframe) and ignored otherwise. Is there a use-case for profiling on a script-by-script basis?

**Comment by acomminos** [comment]
Punting this from L1, we can revisit whether or not we need this at a later time.
