### ISSUE TITLE
Marker support

### ISSUE THREAD

**Issue by jesup** [vdjeric/js-self-profiling#3]
In the Gecko Profiler, in addition to time-based stack sampling, we also insert markers for all sorts of things, with JSON information about what it is (GC stats, etc).

It would be handy to be able do from your JS:
`  Profiler.insertMarker(type, json_data)` or `  Profiler.insertMarker(type, start, end, json_data)`
and have a marker inserted into the profile data with a timestamp based on the current time.
To ease display in tools, it might be handy to also allow 
`  Profiler.setMarkerSchema(type, schema)`
to give tools the basics of how to deal with and display the marker JSON.

That would also give profilers the option of exposing some (safe) data in markers.

**Comment by vdjeric** [comment]
Marker functionality is very desirable, and I mentioned support for performance.mark() in the collected profile as a wishlist feature. Is there a need to distinguish between performance.mark/.measure and Profiler.insertMarker?

**Comment by acomminos** [comment]
As discussed at TPAC, since we share the same time origin as user timing this is redundant. Closing.
