### ISSUE TITLE
ProfilerFrame.label description

### ISSUE THREAD

**Issue by npm1** [vdjeric/js-self-profiling#6]
The current description of ProfilerFrame.label is a bit vague. For example, it says that the data can have "an arbitrary encoding". I think the description of the label should be much more precise so that:

1. Browser vendors can agree on the shape of the label and data could be aggregated if desired.
2. It's feasible to test correctness of labels in web platform tests.

**Comment by acomminos** [comment]
We chose not to include a canonical format in the spec both for ease of implementation (leveraging existing stack formatting code for `Error.stack` output, which already varies widely across browsers), as well as figuring that such a format might be more suited for declaration in a standalone spec for more focused discussion and reuse. Many sites already have logic for aggregating cross-browser `Error.stack` output, and I believe that we should be able to provide adequate web platform tests by doing simple string searches.

I agree that it'd be very useful, though. I'll look at making `ProfilerFrame.label` more constrained while retaining these properties.

**Comment by acomminos** [comment]
We decided at TPAC to standardize the stack frame format- closing.
