### ISSUE TITLE
stop() could produce too much memory

### ISSUE THREAD

**Issue by npm1** [vdjeric/js-self-profiling#7]
It's my understanding that the stop() method will return all of the data. If developers are not careful and profile a large website for a long period of time, the object will be extremely big and I'd expect crashes could be frequent. I would consider setting a limit on the size of the ProfilerTrace (so profiling would simply stop once the trace reaches a certain size), or somehow chunking the trace into separate components that are not all returned at once from the same method.

**Comment by acomminos** [comment]
Initially we thought that recommending the UA silently stop recording when an opaque implementation-defined limit was reached would be fine, but I like your idea better. What are your thoughts on an exposed `Profiler.sampleCapacity` property, which would be chosen by the UA? I suspect it would be sufficient to only bound the number of samples and not stack/frame length.

**Comment by npm1** [comment]
I suppose in practice bounding the number of samples could suffice since the depth shouldn't be arbitrarily long. Is |frames| + |stacks| + |samples| a more accurate measure of the amount of memory used (but less intuitive)? Maybe the capacity could be a certain small default value (set by the UA or the spec) and the user could change the value according to their needs. This makes it flexible and forces developers that want to spend a lot of memory on it to actually request for it explicitly (of course with the obvious risks of laggy user experiences or even the UA running out of memory).
